services:
  quiz.manager:
    class: Smirik\QuizBundle\Manager\QuizManager
  user_quiz.manager:
    class: Smirik\QuizBundle\Manager\UserQuizManager
  user_question.manager:
    class: Smirik\QuizBundle\Manager\UserQuestionManager

  quiz.configure_menu_listener:
      class: Smirik\QuizBundle\Listener\ConfigureMenuListener
      arguments: ["@security.context", "@translator"]
      tags:
        - { name: kernel.event_listener, event: admin.menu_configure, method: onMenuConfigure }    
        - { name: kernel.event_listener, event: main.menu_configure, method: onMainMenuConfigure }    